# steps:
# - name: golang
#   args: ["go","build", "-o","go-app","." ]

# artifacts:
#   objects:
#     location: gs://go-app-artifacts/
#     paths: ["./go-app"]

steps:
- name: golang
  args: [ "go", "build", "-o", "go-app", "." ]

artifacts:
  objects:
    location: gs://go-artifacts-03/
    paths: [ "./go-app" ]

options:
  logging: CLOUD_LOGGING_ONLY
